indeedeng/Mariner

- exampleData/mini.json
- src/dependency-details-retreiver.ts
- src/indexExample.ts
- src/owner-data-collection.ts
Also adds sample data and an example file a person can use to test running this library, with instructions on how to use it.
The i/o filenames and GitHub token will be environment variables if using the example file (indexExample)
> Parameterize i/o filenames

- README.md
- package-lock.json
- package.json
Updates the README. Also includes minor changes to package.json (bringing in typescript types to fix a lint error related to process, and rearranging the sections).
> Osst 942 readme changes

- src/dependency-details-retriever.ts
Co-authored-by: Kevin Smith <45774061+kevindigo@users.noreply.github.com>
> removed return value from run()

- src/indexExample.ts
- src/tab-level-logger.ts
dont let the weird branch name throw you off (my mistake)
> Created Logger Interface and added example logger

- src/dependency-details-retriever.ts
- src/http.ts
- src/tab-level-logger.ts
Log errors and continue. 
More detailed error logging.
> Improve error handling

- package.json
patch update to version number
> update version number due to lodash update

- README.md
- package-lock.json
Co-authored-by: Kevin Smith <45774061+kevindigo@users.noreply.github.com>
> updated version in package.lock.json and tweaked readme

- src/gitHubIssueFetcher.ts
- src/indexExample2.ts
- src/issueFinder.ts
Co-authored-by: Kevin Smith <45774061+kevindigo@users.noreply.github.com>
> Edited Issue and GitHubIssue Interface, converted github issue to 'our' issue

- src/gitHubIssueFetcher.ts
This initial work has a small hard-coded page size (10) so we can see that it is working. I'm not sure what else would need to be changed before it is ready to merge.
> Initial rough implementation of pagination

- .nvmrc
- src/issueFinder.ts
- tsconfig.json
refactored code to loop through all passed labels and added if statement to deal with undefined object
> loop through all the passed labels

- src/gitHubIssueFetcher.ts
- src/indexExample2.ts
- src/issueFinder.ts
…GitHubIssue array, removed mariner.logger, added more labels, error handling if edge.node.repository was missing
> Fetcher should split the repos

- examples/runFasterCode.ts
merged 1105 and resolved merge conflicts, created functions to convert map to Record and output to json
> OSST1104- Output the results to an output file 

- README.md
Co-authored-by: IngridGdesigns <aleja.morada@gmail.com>
> Add step-by-step instructions for using mariner.

- package-lock.json
- package.json
- src/gitHubIssueFetcher.ts
- src/issueFinder.ts
Fix a couple unused imports, and bump the version number.
> Publish 0.3.1 alpha

- package-lock.json
- package.json
- src/gitHubIssueFetcher.ts
> updated version to 0.3.2  in package.json and package-lock.json

- package-lock.json
- package.json
Updated dependencies:
```
@octokit/graphql                    ^4.5.5  →    ^4.5.6
@types/node-fetch                   ^2.5.5  →    ^2.5.7
moment                             ^2.24.0  →   ^2.29.0
typescript                          ^3.8.3  →    ^4.0.3
@types/node                       ^13.13.2  →  ^14.11.2
@typescript-eslint/eslint-plugin   ^2.28.0  →    ^4.3.0
@typescript-eslint/parser          ^2.28.0  →    ^4.3.0
eslint                              ^6.8.0  →   ^7.10.0
eslint-config-prettier             ^6.10.1  →   ^6.12.0
eslint-plugin-prettier              ^3.1.3  →    ^3.1.4
prettier                            ^2.0.4  →    ^2.1.2
```
> Update Dependencies to latest

- .eslintrc.json
- src/dependency-details-retriever.ts
- src/gitHubIssueFetcher.ts
- src/owner-data-collection.ts
- src/request-queue.ts
A series of commits, each of which fixes a lint error (or in one case prevents a future lint error).
> Osst 1140 fix lint errors

- .eslintrc.json
- examples/runFasterCode.ts
- jest.config.js
- package-lock.json
- package.json
- src/Utilities/generateConfluenceMarkdown.ts
- src/__tests__/generateConfluenceMarkdown.test.ts
added types to forEach loop, 
added Utilities file ,
converted code in file to Typescript
Co-authored-by: Kevin Smith <45774061+kevindigo@users.noreply.github.com>
> bringing in generate markdown code from Mariner Issue Collector

- .gitignore
- README.md
- examples/config.json
- examples/runFasterCode.ts
- src/Utilities/generateConfluenceMarkdown.ts
- src/__tests__/generateConfluenceMarkdown.test.ts
- src/config.ts
- src/mariner/index.ts
update the oss-mariner readme to reflect this new feature added
> Update read me with new feature changes - generateConfluenceMarkdown - removing curly braces & brackets, exporting feature

- README.md
- examples/config.json
- examples/runFasterCode.ts
- src/config.ts
made markdownPath to a const in runFasterCode.js file
> removed confluenceMarkdownPath from config

- src/Utilities/generateConfluenceMarkdown.ts
- src/__tests__/generateConfluenceMarkdown.test.ts
WIP: 
tests are broken at the moment due to code change
> edited code to output a dependency within the date range

- README.md
- src/Utilities/generateConfluenceMarkdown.ts
- src/__tests__/generateConfluenceMarkdown.test.ts
replaced them with parentheses
> Remove square brackets and curly braces

- package-lock.json
- package.json
Co-authored-by: Kevin Smith <kevindigo@users.noreply.github.com>
> update to new version 0.5.0-beta

- src/gitHubIssueFetcher.ts
- replaced with getLogger().info()
> Replaced unhelpful console.log() with more informative output through the standard logger

- README.md
- package-lock.json
- package.json
- edited steps in publish section
- updated version
> Publish 0.5.1 beta

- src/gitHubIssueFetcher.ts
Replace a tab character with 4 spaces.
> Replace extraneous tab

- README.md
edited publish steps to have the dry run before the login
> Closes #80

- README.md
- src/Utilities/generateConfluenceMarkup.ts
- src/Utilities/generateGitHubMarkdown.ts
- src/Utilities/generateHtml.ts
- src/Utilities/outputHelpers.ts
- src/__tests__/generateConfluenceMarkup.test.ts
- src/__tests__/generateGitHubMarkdown.test.ts
- src/mariner/index.ts
> Markdown file

- package-lock.json
- package.json
- src/http.ts
- tsconfig.json
removed node-fetch and type
added axios and edited code
added DOM in compilerOptions to deal with typescript error
> Closes #113 - replaced node-fetch with axios

- src/issueFinder.ts
> add IssuesByRepoName type

- .nvmrc
> Fixes #121

- .husky/pre-commit
- .nvmrc
> updated node version

- src/gitHubIssueFetcher.ts
- src/issueFinder.ts
added new interface and assignees
> omitting issues that are already assigned
